name: my-first-workflow
on: push 
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps: 
        - name: checkout repo
          uses: actions/checkout@v6
          
        - name: Welcome message
          run: echo " hi this is a my first github action"
        
        - name: List files
          run: ls

        - name: Read-file
          run: cat READEME.md